### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by meyerzinn** [InventivetalentDev/Quarry#3]
I have updated the plugin for 1.14.1 and fixed various issues with the GUI menu and whatnot. What is the license for this plugin and will you allow a pull request to fix it?

**Comment by InventivetalentDev** [comment]
absolutely, thanks! License is MIT :)

**Comment by TallGreenMario** [comment]
@20zinnm have you updated the plugin yet? would like a copy of it for my server. The GUI isn't working, I cant start the quarry by clicking or anything like that, Thanks again.

**Comment by meyerzinn** [comment]
@TallGreenMario I'm actually working on a rewrite based on my experience with the plugin on a server. I've found that as-is, the quarries are hugely unbalanced. I can submit a PR with the basic fixes I made to make it compile and have basic functionality, but I'm not focused on this repo.

**Comment by meyerzinn** [comment]
@TallGreenMario https://github.com/20zinnm/AutoQuarry
As of now, you have to build it yourself (I'm still bug-testing and adding features), but it's functional on my private server.

I definitely would appreciate any feedback and especially bug reports--this is my first Minecraft plugin since 1.8ish, so things have changed a bit.

**Comment by meyerzinn** [comment]
Some key differences:
- Fuel is required for the quarry to operate (loaded by hopper)
- Quarries are portable--when broken, they take their upgrades and fuel with them
- uses the persistence API to ensure quarries are not lost if the JSON file is out of sync for whatever reason
- upgrades cost $$$ (meant to make the plugin play nice with server economies, configuration TODO)
- the GUI works
- more granular filters and configurable limits on what blocks can be mined
- quarries are more balanced -- way slower by default
